
package vista;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Kaleluwu
 */
public class GestionCitaMedica extends javax.swing.JFrame {

    /**
     * Creates new form GestionCitaMedica
     */
    public GestionCitaMedica() {
        initComponents();
        setTitle("Gestión Citas Médicas");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnAgregarSpaCan = new javax.swing.JButton();
        btnEditarSpaCan = new javax.swing.JButton();
        btnLimpiarSpaCan = new javax.swing.JButton();
        btnEliminarSpaCan = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Cita", "Mascota", "Personal Médico", "Nombre: ", "Fecha", "Hora", "Estado de Cita"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 137, 690, 333));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("GESTIÓN DE CITAS ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 18, -1, -1));

        jLabel1.setText("Buscar");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 83, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 78, 118, -1));

        jButton1.setBackground(new java.awt.Color(0, 122, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 78, -1, -1));

        btnAgregarSpaCan.setBackground(new java.awt.Color(107, 193, 34));
        btnAgregarSpaCan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarSpaCan.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarSpaCan.setText("Nueva Cita");
        btnAgregarSpaCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSpaCanActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarSpaCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 476, 90, 30));

        btnEditarSpaCan.setBackground(new java.awt.Color(254, 183, 7));
        btnEditarSpaCan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarSpaCan.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarSpaCan.setText("Editar");
        btnEditarSpaCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSpaCanActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditarSpaCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 476, 90, 30));

        btnLimpiarSpaCan.setBackground(new java.awt.Color(102, 102, 102));
        btnLimpiarSpaCan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarSpaCan.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarSpaCan.setText("Limpiar");
        btnLimpiarSpaCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarSpaCanActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiarSpaCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 476, 90, 30));

        btnEliminarSpaCan.setBackground(new java.awt.Color(254, 0, 0));
        btnEliminarSpaCan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarSpaCan.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarSpaCan.setText("Eliminar");
        btnEliminarSpaCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSpaCanActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarSpaCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 476, 90, 30));

        btnregresar.setBackground(new java.awt.Color(0, 145, 145));
        btnregresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnregresar.setForeground(new java.awt.Color(255, 255, 255));
        btnregresar.setText("REGRESAR");
        btnregresar.setBorder(null);
        jPanel2.add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarSpaCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSpaCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarSpaCanActionPerformed

    private void btnEditarSpaCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSpaCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSpaCanActionPerformed

    private void btnLimpiarSpaCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarSpaCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarSpaCanActionPerformed

    private void btnEliminarSpaCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSpaCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSpaCanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCitaMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSpaCan;
    private javax.swing.JButton btnEditarSpaCan;
    private javax.swing.JButton btnEliminarSpaCan;
    private javax.swing.JButton btnLimpiarSpaCan;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
