/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.LoginControlador;
import java.awt.Color;
import com.formdev.flatlaf.*;
import java.awt.Image;
import java.awt.Toolkit;
public class Login extends javax.swing.JFrame {

    private final LoginControlador controlador;
    
    public Login() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        lbltitulo.setFocusable(true);
        controlador = new LoginControlador(this); 
        txtuser.addKeyListener(controlador);
        pswuser.addKeyListener(controlador);
        Image imagen=Toolkit.getDefaultToolkit().getImage("src\\main\\java\\images\\iconvet.png");
        setIconImage(imagen);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblimagen = new javax.swing.JLabel();
        lbliniciar = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        lblclave = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        panelverde = new javax.swing.JPanel();
        pswuser = new javax.swing.JPasswordField();
        paneltitulo = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        btnacceder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bgKeyPressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblimagen.setIcon(new javax.swing.ImageIcon("src\\main\\java\\images\\loginvet.png"));
        bg.add(lblimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 180, 410));

        lbliniciar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbliniciar.setText("INICIAR SESIÓN");
        bg.add(lbliniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 34));

        lbluser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbluser.setText("USUARIO");
        bg.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        lblclave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblclave.setText("CONTRASEÑA");
        bg.add(lblclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        txtuser.setForeground(new java.awt.Color(204, 204, 204));
        txtuser.setText("Ingrese su usuario");
        txtuser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtuser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtuserMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        bg.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 240, 26));

        panelverde.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout panelverdeLayout = new javax.swing.GroupLayout(panelverde);
        panelverde.setLayout(panelverdeLayout);
        panelverdeLayout.setHorizontalGroup(
            panelverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        panelverdeLayout.setVerticalGroup(
            panelverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        bg.add(panelverde, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 112, -1, -1));

        pswuser.setForeground(new java.awt.Color(204, 204, 204));
        pswuser.setText("***********");
        pswuser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pswuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pswuserMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pswuserMousePressed(evt);
            }
        });
        pswuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswuserActionPerformed(evt);
            }
        });
        bg.add(pswuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 240, 28));

        paneltitulo.setBackground(new java.awt.Color(234, 245, 218));
        paneltitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setBackground(new java.awt.Color(229, 244, 234));
        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("VETERINARIA D' POCAS PULGAS");
        paneltitulo.add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 6, -1, 38));

        bg.add(paneltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 24, 380, 50));

        btnacceder.setBackground(new java.awt.Color(108, 193, 34));
        btnacceder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnacceder.setForeground(new java.awt.Color(255, 255, 255));
        btnacceder.setText("ACCEDER");
        btnacceder.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnacceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnacceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaccederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaccederMouseExited(evt);
            }
        });
        btnacceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccederActionPerformed(evt);
            }
        });
        bg.add(btnacceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void pswuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswuserActionPerformed

    
    private void txtuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMouseClicked
        
    }//GEN-LAST:event_txtuserMouseClicked

    private void pswuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswuserMouseClicked

    }//GEN-LAST:event_pswuserMouseClicked

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
        if(txtuser.getText().equals("Ingrese su usuario")){
            txtuser.setText("");
            txtuser.setForeground(Color.BLACK);
        }
        if(String.valueOf(pswuser.getPassword()).isEmpty()){
            pswuser.setText("***********");
            pswuser.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtuserMousePressed

    private void pswuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswuserMousePressed
        if(String.valueOf(pswuser.getPassword()).equals("***********")){
            pswuser.setText("");
            pswuser.setForeground(Color.BLACK);
        }
        if(txtuser.getText().isEmpty()){
            txtuser.setText("Ingrese su usuario");
            txtuser.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_pswuserMousePressed

    private void bgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bgKeyPressed
        
    }//GEN-LAST:event_bgKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed

    private void btnaccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccederActionPerformed
        controlador.actionPerformed(evt);
    }//GEN-LAST:event_btnaccederActionPerformed

    private void btnaccederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccederMouseEntered
        btnacceder.setBackground(new Color(90,161,28));
    }//GEN-LAST:event_btnaccederMouseEntered

    private void btnaccederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccederMouseExited
        btnacceder.setBackground(new Color(108,193,34));
    }//GEN-LAST:event_btnaccederMouseExited

    private void bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bgMouseClicked

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        if(txtuser.getText().isEmpty()){
            txtuser.setText("Ingrese su usuario");
            txtuser.setForeground(Color.GRAY);
        }
        
        if(String.valueOf(pswuser.getPassword()).isEmpty()){
            pswuser.setText("***********");
            pswuser.setForeground(Color.GRAY);
        }
        lbltitulo.setFocusable(true);
    }//GEN-LAST:event_bgMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    public javax.swing.JButton btnacceder;
    private javax.swing.JLabel lblclave;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JLabel lbliniciar;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbluser;
    private javax.swing.JPanel paneltitulo;
    private javax.swing.JPanel panelverde;
    public javax.swing.JPasswordField pswuser;
    public javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
