/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import vista.*;

/**
 *
 * @author EMNA
 */
public class RegistrarMascota extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarMascota
     */
    public RegistrarMascota() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelpropietario = new javax.swing.JPanel();
        lblidcli = new javax.swing.JLabel();
        lblnombrecli = new javax.swing.JLabel();
        lblapcli = new javax.swing.JLabel();
        txtidcli = new javax.swing.JTextField();
        txtnombrecli = new javax.swing.JTextField();
        txtapcli = new javax.swing.JTextField();
        panelregistromascota = new javax.swing.JPanel();
        lblnombremascota = new javax.swing.JLabel();
        lblespecie = new javax.swing.JLabel();
        lblraza = new javax.swing.JLabel();
        lblsexo = new javax.swing.JLabel();
        lbldes = new javax.swing.JLabel();
        txtnombremascota = new javax.swing.JTextField();
        cbxsexo = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        cbxespecie = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        areatxtdes = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        lblimagen = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbldatos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelpropietario.setBackground(new java.awt.Color(255, 255, 255));
        panelpropietario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROPIETARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        panelpropietario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblidcli.setText("ID cliente");
        panelpropietario.add(lblidcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lblnombrecli.setText("Nombres");
        panelpropietario.add(lblnombrecli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lblapcli.setText("Apellidos");
        panelpropietario.add(lblapcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        panelpropietario.add(txtidcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 230, -1));
        panelpropietario.add(txtnombrecli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 230, -1));

        txtapcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapcliActionPerformed(evt);
            }
        });
        panelpropietario.add(txtapcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, -1));

        jPanel1.add(panelpropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 380, 170));

        panelregistromascota.setBackground(new java.awt.Color(255, 255, 255));
        panelregistromascota.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE MASCOTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        panelregistromascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnombremascota.setText("Nombre");
        panelregistromascota.add(lblnombremascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblespecie.setText("Especie");
        panelregistromascota.add(lblespecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblraza.setText("Raza");
        panelregistromascota.add(lblraza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lblsexo.setText("Sexo");
        panelregistromascota.add(lblsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lbldes.setText("Descripción");
        panelregistromascota.add(lbldes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        panelregistromascota.add(txtnombremascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, -1));

        cbxsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione -", "HEMBRA", "MACHO" }));
        panelregistromascota.add(cbxsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 240, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione -" }));
        panelregistromascota.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 240, -1));

        cbxespecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione -", "PERRO", "GATO", "OTRO" }));
        panelregistromascota.add(cbxespecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 240, -1));

        areatxtdes.setColumns(20);
        areatxtdes.setRows(5);
        jScrollPane1.setViewportView(areatxtdes);

        panelregistromascota.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 240, 80));

        jButton3.setText("Seleccionar archivo");
        panelregistromascota.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        lblimagen.setText("Imagen");
        panelregistromascota.add(lblimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 50, -1));

        jPanel1.add(panelregistromascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 380, 380));

        btnregresar.setBackground(new java.awt.Color(0, 145, 145));
        btnregresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnregresar.setForeground(new java.awt.Color(255, 255, 255));
        btnregresar.setText("REGRESAR");
        btnregresar.setBorder(null);
        jPanel1.add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        btnagregar.setBackground(new java.awt.Color(108, 193, 34));
        btnagregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setText("+ Agregar");
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 100, 30));

        btneditar.setBackground(new java.awt.Color(255, 183, 7));
        btneditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneditar.setForeground(new java.awt.Color(255, 255, 255));
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jPanel1.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 670, 100, 30));

        btnlimpiar.setBackground(new java.awt.Color(51, 51, 51));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setText("Limpiar");
        jPanel1.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, 100, 30));

        btneliminar.setBackground(new java.awt.Color(255, 0, 0));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar ");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 670, 100, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MASCOTAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(238, 238, 251));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder()));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Sexo");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 128, -1, -1));

        jLabel14.setText("Descripción");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 162, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("POLAR");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 17, -1, -1));

        jLabel11.setText("Especie");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 60, -1, -1));

        jLabel12.setText("Raza");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 94, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("src\\main\\java\\images\\chowchow.png"));
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 60, 140, 170));

        lbldatos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldatos.setText("DATOS DE LA MASCOTA");
        jPanel4.add(lbldatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 530, 220));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 610, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapcliActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areatxtdes;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JComboBox<String> cbxespecie;
    private javax.swing.JComboBox<String> cbxsexo;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblapcli;
    private javax.swing.JLabel lbldatos;
    private javax.swing.JLabel lbldes;
    private javax.swing.JLabel lblespecie;
    private javax.swing.JLabel lblidcli;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JLabel lblnombrecli;
    private javax.swing.JLabel lblnombremascota;
    private javax.swing.JLabel lblraza;
    private javax.swing.JLabel lblsexo;
    private javax.swing.JPanel panelpropietario;
    private javax.swing.JPanel panelregistromascota;
    private javax.swing.JTextField txtapcli;
    private javax.swing.JTextField txtidcli;
    private javax.swing.JTextField txtnombrecli;
    private javax.swing.JTextField txtnombremascota;
    // End of variables declaration//GEN-END:variables
}
