/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import controlador.RegistarClienteControlador;
import java.awt.LayoutManager;

/**
 *
 * @author EMNA
 */
public class RegistrarCliente extends javax.swing.JFrame {

    private RegistarClienteControlador registrarClienteControlador;

    /**
     * Creates new form RegistrarCliente
     */
    public RegistrarCliente() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        Image imagen = Toolkit.getDefaultToolkit().getImage("src\\main\\java\\images\\iconvet.png");
        setIconImage(imagen);
        registrarClienteControlador = new RegistarClienteControlador(this);
        try{
        registrarClienteControlador.listarDistritos();
        }catch(Exception e){
            System.out.println("");
        }
               
    }

    public JTable getTablaclientes() {
        return tablaclientes;
    }

    public void setTablaclientes(JTable tablaclientes) {
        this.tablaclientes = tablaclientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        bg = new javax.swing.JPanel();
        plregistrocliente = new javax.swing.JPanel();
        lblap = new javax.swing.JLabel();
        lblnom = new javax.swing.JLabel();
        lbltipodoc = new javax.swing.JLabel();
        lblnumdoc = new javax.swing.JLabel();
        lblcel = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        lbldistrito = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        txtappat = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtnumdoc = new javax.swing.JTextField();
        cbxtipodoc = new javax.swing.JComboBox<>();
        txtcel = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        cbxdistrito = new javax.swing.JComboBox<>();
        txtdireccion = new javax.swing.JTextField();
        txtapmat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblclientes = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaclientes = new javax.swing.JTable();
        btneditar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        lblbuscar = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        btncargardatos = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plregistrocliente.setBackground(new java.awt.Color(255, 255, 255));
        plregistrocliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE CLIENTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        plregistrocliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblap.setText("Apellido paterno");
        plregistrocliente.add(lblap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblnom.setText("Nombres");
        plregistrocliente.add(lblnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lbltipodoc.setText("Tipo de documento");
        plregistrocliente.add(lbltipodoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lblnumdoc.setText("N° de documento");
        plregistrocliente.add(lblnumdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        lblcel.setText("Celular");
        plregistrocliente.add(lblcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblcorreo.setText("Correo electrónico");
        plregistrocliente.add(lblcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, -1));

        lbldistrito.setText("Distrito");
        plregistrocliente.add(lbldistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        lbldireccion.setText("Dirección");
        plregistrocliente.add(lbldireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));
        plregistrocliente.add(txtappat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 200, -1));
        plregistrocliente.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, -1));

        txtnumdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumdocActionPerformed(evt);
            }
        });
        plregistrocliente.add(txtnumdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 200, -1));

        cbxtipodoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione -", "DNI", "Carnet de extranjería " }));
        plregistrocliente.add(cbxtipodoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, -1));
        plregistrocliente.add(txtcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 200, -1));

        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        plregistrocliente.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 200, -1));

        cbxdistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione -" }));
        plregistrocliente.add(cbxdistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 200, -1));

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        plregistrocliente.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 200, -1));
        plregistrocliente.add(txtapmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 200, -1));

        jLabel1.setText("Apellido materno");
        plregistrocliente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        bg.add(plregistrocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 430, 430));

        lblclientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblclientes.setText("LISTA DE CLIENTES");
        bg.add(lblclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, -1));

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        bg.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 150, -1));

        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Apellido paterno", "Apellido materno", "Nombres", "Tipo doc.", "Nro doc.", "Celular", "Correo", "Dirección", "Distrito"
            }
        ));
        tablaclientes.getColumnModel().getColumn(9).setCellRenderer(new DefaultTableCellRenderer(){

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel mascotas = new JLabel("+ mascota");
                mascotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                return mascotas;
            }
        });
        tablaclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaclientes);
        if (tablaclientes.getColumnModel().getColumnCount() > 0) {
            tablaclientes.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablaclientes.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 1000, 430));

        btneditar.setBackground(new java.awt.Color(255, 183, 7));
        btneditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneditar.setForeground(new java.awt.Color(255, 255, 255));
        btneditar.setText("Editar");
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        bg.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 100, 30));

        btnlimpiar.setBackground(new java.awt.Color(51, 51, 51));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setText("Limpiar");
        btnlimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        bg.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 100, 30));

        btneliminar.setBackground(new java.awt.Color(255, 0, 0));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar ");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        bg.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 100, 30));

        lblbuscar.setText("Buscar cliente por N° doc");
        bg.add(lblbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, 30));

        btnbuscar.setBackground(new java.awt.Color(0, 122, 255));
        btnbuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setText("Buscar");
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        bg.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 100, 30));

        btnregresar.setBackground(new java.awt.Color(0, 145, 145));
        btnregresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnregresar.setForeground(new java.awt.Color(255, 255, 255));
        btnregresar.setText("REGRESAR");
        btnregresar.setBorder(null);
        bg.add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        btnagregar.setBackground(new java.awt.Color(108, 193, 34));
        btnagregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setText("+ Agregar");
        btnagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        bg.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 100, 30));

        btncargardatos.setText("O");
        btncargardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargardatosActionPerformed(evt);
            }
        });
        bg.add(btncargardatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 70, 30, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void txtnumdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumdocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumdocActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        try {
            registrarClienteControlador.editar(this);
            limpiar();
        } catch (Exception e) {
            System.err.println(e);
        }  
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        try {
            registrarClienteControlador.eliminar(this);
            limpiar();
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        try {
            registrarClienteControlador.buscar(this);
            limpiar();
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void tablaclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaclientesMouseClicked
        try {
            txtapmat.setEditable(false);
            txtappat.setEditable(false);
            txtnom.setEditable(false);
            cbxtipodoc.setEnabled(false);
            txtnumdoc.setEditable(false);
            registrarClienteControlador.ver(this);
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_tablaclientesMouseClicked

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        try {
            registrarClienteControlador.crear(this);
            limpiar();
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        tablaclientes.clearSelection();
    }//GEN-LAST:event_bgMousePressed

    private void btncargardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargardatosActionPerformed
        txtbuscar.setText("");
        try {
            registrarClienteControlador.listar(this);
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btncargardatosActionPerformed

    
    public void limpiar(){
        txtappat.setText("");
        txtapmat.setText("");
        txtnom.setText("");
        cbxtipodoc.setSelectedIndex(0);
        txtnumdoc.setText("");
        txtcel.setText("");
        txtcorreo.setText("");
        txtdireccion.setText("");
        cbxdistrito.setSelectedIndex(0);
        txtapmat.setEditable(true);
        txtappat.setEditable(true);
        txtnom.setEditable(true);
        cbxtipodoc.setEnabled(true);
        txtnumdoc.setEditable(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                RegistrarCliente registrarCliente = new RegistrarCliente();
                RegistarClienteControlador registrarClienteControlador;
                registrarClienteControlador = new RegistarClienteControlador(registrarCliente);
                try {
                    registrarClienteControlador.listar(registrarCliente);
                } catch (Exception e) {
                    System.err.println(e);
                }
                registrarCliente.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncargardatos;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnregresar;
    public javax.swing.JComboBox<String> cbxdistrito;
    public javax.swing.JComboBox<String> cbxtipodoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblap;
    private javax.swing.JLabel lblbuscar;
    private javax.swing.JLabel lblcel;
    private javax.swing.JLabel lblclientes;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lbldistrito;
    private javax.swing.JLabel lblnom;
    private javax.swing.JLabel lblnumdoc;
    private javax.swing.JLabel lbltipodoc;
    private javax.swing.JPanel plregistrocliente;
    public javax.swing.JTable tablaclientes;
    public javax.swing.JTextField txtapmat;
    public javax.swing.JTextField txtappat;
    public javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtcel;
    public javax.swing.JTextField txtcorreo;
    public javax.swing.JTextField txtdireccion;
    public javax.swing.JTextField txtnom;
    public javax.swing.JTextField txtnumdoc;
    // End of variables declaration//GEN-END:variables
}
